---
- name: Create Dozzle Docker Container
  community.docker.docker_container:
    name: dozzle
    image: amir20/dozzle:latest
    recreate: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart_policy: unless-stopped
    env:
      DOZZLE_USERNAME: "{{ admin_username }}"
      DOZZLE_PASSWORD: "{{ admin_userpassword }}"
      DOZZLE_KEY: "{{ proxy_user }}"
      DOZZLE_NO_ANALYTICS: "true"
    labels:
      traefik.enable: "{{ dozzle_available_externally }}"
      traefik.http.routers.dozzle.rule: "Host(`{{ dozzle_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.dozzle.loadbalancer.server.port: "8080"
      traefik.http.routers.dozzle.middlewares: "secure-headers@file"
