---
# TODO: refactor this
# - name: Disable recommended packages
#   shell: echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/00norecommends

# - name: Disable suggested packages
#   shell: echo 'APT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01nosuggests

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Install some packages
  apt:
    name: "{{ mayurifag_general_extra_packages }}"
    state: present
    force_apt_get: yes
  register: result
  until: result is succeeded

- name: Upgrade all packages
  apt:
    upgrade: dist
    state: latest
    force_apt_get: yes
  when: keep_packages_updated
  tags:
    - skip_ansible_lint

- name: Check if a reboot is needed on all servers
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

- name: Automatically remove any unused dependencies
  apt:
    autoremove: true
