---
# TODO: show only if enabled
- name: Show cheatsheet
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      ===============================
      Further notes on installation
      ===============================

      ### Telegram proxy link

      https://t.me/socks?server={{ server_hostname }}&port={{ proxy_port }}&user={{ proxy_user }}&pass={{ proxy_user_password }}

      ### SSH

      Dont forget to change SSH configuration (user, etc.)
      $ ssh mayurifag-prod

      ### Wallabag

      Change default user's password from `wallabag:wallabag` into anything else.

      ### Portainer

      Make user and add default docker entrypoint.

      ### SFTPGo

      Set {{ admin_username }} user with password, add directory.

      ### Files (Filebrowser/OCIS)

      You have to sync files now via app. Setup iOS/Android/Mac/Win(?)
      Sync bookmarks via floccus
      Make keepassxc use new kdbx

      ### Filebrowser

      Update password. Default are admin:admin
      Set dark theme.

      ### Shadowsocks

      Download xray-plugin and make sure it is may be launched through

      # ss: client.json
      {
        "server": "{{ shadowsocks_subdomain }}.{{ server_hostname }}",
        "server_port": 443,
        "local_port": 1080,
        "password": "{{ shadowsocks_password }}",
        "method": "{{ shadowsocks_encrypt_method }}",
        "plugin": "{{ shadowsocks_plugin }}",
        "fast_open": true,
        "mode": "tcp_and_udp",
        "no_delay": true,
        "plugin_opts": "path=/xray;mux=8;host={{ shadowsocks_subdomain }}.{{ server_hostname }};tls"
      }

      ### DNS

      TODO: set DNS to ip of this host

      =========================
