---
- name: cleanup packaging
  apt:
    autoclean: yes
    autoremove: yes

- name: Show cheatsheet
  pause:
    seconds: 1
    prompt: |
      =========================

      https://t.me/socks?server={{ server_hostname }}&port=7777&user={{ proxy_user }}&pass={{ proxy_user_password }}

      #####

      Dont forget to

      1) ssh configuration
      2) Make configuration which is stated in Homer service change password

      =========================
