---
- name: cleanup packaging
  apt:
    autoclean: yes
    autoremove: yes

- name: restart danted
  systemd: name=danted state=restarted

- name: Show cheatsheet
  pause:
    seconds: 1
    prompt: |
      =========================

      https://t.me/socks?server={{ server_hostname }}&port=7777&user={{ proxy_user }}&pass={{ proxy_user_password }}

      =========================
