---
- name: Provisioning
  hosts: sample
  gather_facts: yes
  become: yes
  roles:
    - role: server_preparations
      tags:
        - general

    - role: swapoff
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: geerlingguy.swap
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: home_folder
      tags:
        - home

    - role: geerlingguy.docker
      tags:
        - docker
      when: (docker_enabled | default(False))

    - role: darkwizard242.lazydocker
      tags:
        - lazydocker
      when: (lazydocker_enabled | default(False))

    - role: lldap
      tags:
        - lldap
      when: (lldap_enabled | default(False))

    - role: tinyauth
      tags:
        - tinyauth
      when: (tinyauth_enabled | default(False))

    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: crowdsec
      tags:
        - crowdsec
      when: (crowdsec_enabled | default(False))

    - role: homepage
      tags:
        - homepage
      when: (homepage_enabled | default(False))

    - role: mayurifag_github_io
      tags:
        - mayurifag_github_io
      when: (mayurifag_github_io_enabled | default(False))

    - role: proxy
      tags:
        - proxy
      when: (proxy_enabled | default(False))

    - role: threexui
      tags:
        - threexui
      when: (threexui_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: mus
      tags:
        - mus
      when: (mus_enabled | default(False))

    - role: opencloud
      tags:
        - opencloud
      when: (opencloud_enabled | default(False))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: bentopdf
      tags:
        - bentopdf
      when: (bentopdf_enabled | default(False))

    - role: convertx
      tags:
        - convertx
      when: (convertx_enabled | default(False))

    - role: mini_qr
      tags:
        - qr
      when: (mini_qr_enabled | default(False))

    - role: linkding
      tags:
        - linkding
      when: (linkding_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))
