---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: robertdebock.bootstrap
      tags:
        - bootstrap
      when: (bootstrap_enabled | default(True))

- hosts: all
  roles:
    ###
    ### Run general preparation
    ###
    - role: djx339.swapoff
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: geerlingguy.swap
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: server-general-preparations
      tags:
        - mayurifag-general

    - role: upgrade-packages
      tags:
        - mayurifag-general

    - role: users
      tags:
        - mayurifag-general

    ###
    ### Requirements
    ###
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: darkwizard242.lazydocker

    ##
    ## Applications
    ##
    - role: dante
      tags:
        - dante
      when: (dante_enabled | default(False))

    - role: shadowsocks
      tags:
        - shadowsocks
      when: (shadowsocks_enabled | default(False))

    - role: wireguard
      tags:
        - wireguard
      when: (wireguard_enabled | default(False))

    ###
    ### Docker applications
    ###
    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: mayurifag_github_io
      tags:
        - mayurifag_github_io
      when: (mayurifag_github_io_enabled | default(False))

    - role: homer
      tags:
        - homer
      when: (homer_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: wallabag
      tags:
        - wallabag
      when: (wallabag_enabled | default(False))

    - role: cheatsheet
