---
- name: Bootstrap
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: robertdebock.bootstrap
      tags:
        - bootstrap
      when: (bootstrap_enabled | default(True))

- name: Provisioning
  hosts: all
  gather_facts: yes
  roles:
    ###
    ### Run general preparation
    ###
    - role: server_general_preparations
      tags:
        - general

    - role: swapoff
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: geerlingguy.swap
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: users
      tags:
        - users
    ###
    ### Requirements
    ###
    # TODO: role requires gather_facts: yes - fix it or change to another role
    # TODO: recheck on clear installation
    # TODO: make cron task to remove unused docker images
    - role: geerlingguy.docker
      tags:
        - docker
      when: (docker_enabled | default(False))

    - role: darkwizard242.lazydocker
      tags:
        - lazydocker
      when: (lazydocker_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    ###
    ### Docker applications
    ###
    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: mayurifag_github_io
      tags:
        - mayurifag_github_io
      when: (mayurifag_github_io_enabled | default(False))

    - role: proxy
      tags:
        - proxy
      when: (proxy_enabled | default(False))

    - role: threexui
      tags:
        - threexui
      when: (threexui_enabled | default(False))

    # TODO: for ubuntu have to disable systemd-resolved service, occupies 53 port
    # TODO: for ubuntu - change resolv.conf
    - role: blocky
      tags:
        - blocky
      when: (blocky_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: mus
      tags:
        - mus
      when: (mus_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: hemmelig
      tags:
        - hemmelig
      when: (hemmelig_enabled | default(False))

    - role: vaultwarden
      tags:
        - vaultwarden
      when: (vaultwarden_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: gitea
      tags:
        - gitea
      when: (gitea_enabled | default(False))

    - role: obsidian_livesync
      tags:
        - obsidian
      when: (obsidian_livesync_enabled | default(False))

    # requires gather_facts: yes
    - role: dockovpn
      tags:
        - dockovpn
      when: (dockovpn_enabled | default(False))
