---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: robertdebock.bootstrap
      tags:
        - bootstrap
      when: (bootstrap_enabled | default(True))

- hosts: all
  roles:
    ###
    ### Run general preparation
    ###
    - role: swapoff
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: geerlingguy.swap
      tags:
        - swap
      when: (swap_enabled | default(False))

    - role: server-general-preparations
      tags:
        - mayurifag-general

    - role: upgrade-packages
      tags:
        - mayurifag-general

    - role: users
      tags:
        - mayurifag-general

    ###
    ### Requirements
    ###
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: darkwizard242.lazydocker

    ##
    ## Applications
    ##
    - role: proxy
      tags:
        - proxy
      when: (proxy_enabled | default(False))

    - role: shadowsocks
      tags:
        - shadowsocks
      when: (shadowsocks_enabled | default(False))

    - role: wireguard
      tags:
        - wireguard
      when: (wireguard_enabled | default(False))

    ###
    ### Docker applications
    ###
    - role: traefik
      tags:
        - traefik
      when: (traefik_enabled | default(False))

    - role: mayurifag_github_io
      tags:
        - mayurifag_github_io
      when: (mayurifag_github_io_enabled | default(False))

    - role: homer
      tags:
        - homer
      when: (homer_enabled | default(False))

    - role: nextcloud
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: glances
      tags:
        - glances
      when: (glances_enabled | default(False))

    - role: portainer
      tags:
        - portainer
      when: (portainer_enabled | default(False))

    - role: watchtower
      tags:
        - watchtower
      when: (watchtower_enabled | default(False))

    - role: netdata
      tags:
        - netdata
      when: (netdata_enabled | default(False))

    - role: doku
      tags:
        - doku
      when: (doku_enabled | default(False))

    - role: whattocommit
      tags:
        - whattocommit
      when: (whattocommit_enabled | default(False))

    - role: wallabag
      tags:
        - wallabag
      when: (wallabag_enabled | default(False))

    - role: dozzle
      tags:
        - dozzle
      when: (dozzle_enabled | default(False))

    - role: filerun
      tags:
        - filerun
      when: (filerun_enabled | default(False))

    - role: navidrome
      tags:
        - navidrome
      when: (navidrome_enabled | default(False))

    # Nextcloud is unable to configure right after install and I dont want to wait untill il will be ok. So moved this section here.
    - role: nextcloud_config
      tags:
        - nextcloud
      when: (nextcloud_enabled | default(False))

    - role: geerlingguy.security

    - role: cheatsheet
