---
- name: geerlingguy.docker
  version: 7.4.1

- name: geerlingguy.security
  version: 2.4.0

- name: robertdebock.bootstrap
  version: 6.2.1

- name: darkwizard242.lazydocker
  version: 2.6.0

- name: geerlingguy.swap
  version: 1.2.0
