---
- name: geerlingguy.docker
  version: 4.1.1

- name: geerlingguy.pip
  version: 2.1.0

- name: geerlingguy.security
  version: 2.0.1

- name: robertdebock.bootstrap
  version: 6.1.1

- name: darkwizard242.lazydocker
  version: 1.0.7

- name: geerlingguy.swap
  version: 1.0.2
