---
- name: geerlingguy.docker
  version: 3.1.2

- name: geerlingguy.pip
  version: 2.1.0

- name: geerlingguy.security
  version: 2.0.1

- name: robertdebock.bootstrap
  version: 5.1.0

- name: darkwizard242.lazydocker
  version: 1.0.7
