---
- name: reload nginx
  service:
    name: "nginx"
    state: reloaded

- name: start php-fpm
  service:
    name: php{{ php_ver }}-fpm
    state: started

- name: restart php-fpm
  service:
    name: php{{ php_ver }}-fpm
    state: restarted
