---
- name: Get external IPv4 address
  ansible.builtin.set_fact:
    external_ipv4: "{{ ansible_default_ipv4.address }}"

- name: DockerVPN Container
  community.docker.docker_container:
    name: dockovpn
    image: alekslitvinenk/openvpn:latest
    pull: true
    capabilities:
      - NET_ADMIN
    ports:
      - "{{ dockovpn_port }}:1194/udp"
      - "{{ dockovpn_client_config_port }}:8080/tcp"
    env:
      HOST_ADDR: "{{ external_ipv4 }}"
    restart_policy: unless-stopped
    memory: "{{ dockovpn_memory }}"
    labels:
      traefik.enable: "{{ dockovpn_available_externally }}"
      traefik.http.routers.dockovpn.rule: "Host(`{{ dockovpn_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.dockovpn.loadbalancer.server.port: "8080"
      traefik.http.routers.dockovpn.middlewares: "secure-headers@file"
