---
threexui_enabled: true

threexui_data_directory: "{{ docker_home }}/3x-ui"
threexui_docker_image: ghcr.io/mhsanaei/3x-ui:v2.9.3

threexui_panel_subdomain: "3x"

threexui_reality_domain: "learn.microsoft.com"

threexui_vmess_aead_forced: "false"
threexui_enable_fail2ban: "true"

threexui_hysteria2_port: 36500

threexui_certs_dumper_image: ldez/traefik-certs-dumper:v2.11.2
threexui_certs_dumper_memory: 64m
threexui_certs_dumped_directory: "{{ threexui_data_directory }}/dumped_certs"
