---
seafile_enabled: true
seafile_available_externally: "true"

# directories
seafile_data_directory: "{{ docker_home }}/seafile"

seafile_subdomain: "seafile"

# username / passwords
seafile_mysql_root_password: "seafile-mysql-pass"
seafile_admin_email: "{{ admin_email }}"
seafile_admin_password: "{{ admin_userpassword }}"

seafile_internal_letsencrypt: "false"

# specs
seafile_memory: 2g
seafile_mysql_memory: 1g
seafile_memcached_memory: 1g
