---
- name: Configure nextcloud
  block:
    - name: set nextcloud system config.php values
      shell: "{{ docker_occ_cmd }} config:system:set {{ item }}"
      loop: "{{ nextcloud_system_config }}"

    - name: "{{ item.state }} {{ item.name }} app"
      shell: "{{ docker_occ_cmd }} app:{{ item.state }} {{ item.name }}"
      loop: "{{ nextcloud_app_config }}"

    - name: backup jobs, upgrade apps and database tuning
      shell: "{{ docker_occ_cmd }} {{ item }}"
      loop:
        - background:cron
        - upgrade
        - app:update --all
        - db:add-missing-indices
        - db:convert-filecache-bigint

- name: create optimize batch job
  copy:
    dest: /usr/local/bin/nextcloud_optimize.sh
    owner: root
    group: root
    mode: 0750
    content: |
      #!/bin/bash
      docker exec nextcloud-redis redis-cli FLUSHALL
      docker exec --user www-data nextcloud php occ files:scan --all
      docker exec --user www-data nextcloud php occ files:scan-app-data
      docker exec --user www-data nextcloud php occ preview:pre-generate
      exit 0

- name: optimize nextcloud cronjob
  cron:
    name: nextcloud optimize
    minute: "15"
    hour: "01"
    user: root
    job: "/usr/local/bin/nextcloud_optimize.sh > /dev/null 2>&1"

- name: nextcloud cronjob
  cron:
    name: nextcloud cronjob
    minute: "*/5"
    user: root
    job: "docker exec --user www-data nextcloud php -f cron.php > /dev/null 2>&1"

- name: run nextcloud cronjob once
  shell: "docker exec --user www-data nextcloud php -f cron.php > /dev/null 2>&1"
