---
- name: Reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Install wireguard repo (Debian)
  apt_repository:
    filename: unstable-wireguard
    repo: 'deb http://deb.debian.org/debian/ unstable main'
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Configure wireguard repo (Debian)
  blockinfile:
    path: /etc/apt/preferences.d/limit-unstable
    create: yes
    block: |-
      Package: *
      Pin: release a=unstable
      Pin-Priority: 150

- name: Install dependencies (Debian)
  apt:
    name:
      - bc
      - linux-headers-{{ ansible_kernel }}
      - software-properties-common
      - qrencode
    state: present

## Enabled at sysctl tweaks already
# - name: Enable net.ipv4.ip_forward
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: 1
#     reload: yes
#     state: present

- name: ensure wireguard packages are installed
  apt:
    name:
      - wireguard
    state: latest
