---
# List of mail domains (you can put as many as you like)
maildb:
  domains:
      # Domain name (i.e. example.com)
    - name: "{{ production_hostname }}"
      # Is this primary domain (if you wish to receive PUSH notifications from it, you should set it to yes)
      # primary: yes
      # List of users associated with that domain
      users:
      # User email - use full email address (i.e. steven@example.com)
      - email: "{{ primary_email }}"
        password: "{{ primary_email_password }}"
      - email: "{{ alias_one_email }}"
        password: "{{ alias_one_email_password }}"
      - email: "{{ personal_email }}"
        password: "{{ personal_email_password }}"
      - email: "{{ postmaster_email }}"
        password: "{{ postmaster_email_password }}"
      - email: "{{ alias_two_email }}"
        password: "{{ alias_two_email_password }}"
      # List aliases associated with that domain (every mail coming to 'from' email will be delivered to 'to' email instead)
      aliases:
      - from: "{{ alias_one_email }}"
        to: "{{ primary_email }}"
      - from: "{{ alias_two_email }}"
        to: "{{ primary_email }}"
