---
- name: Include hostname configuration
  ansible.builtin.include_tasks: hostname.yml

- name: Include timezone and locales tasks
  ansible.builtin.include_tasks: timezone_locales.yml

- name: Include sysctl configuration tasks
  ansible.builtin.import_tasks: sysctl.yml
  tags:
    - sysctl
    - swap

- name: Include swap configuration tasks
  ansible.builtin.import_tasks: swap.yml
  tags:
    - swap

- name: Include transparent hugepage tasks
  ansible.builtin.import_tasks: transparent_hugepage.yml
  tags:
    - transparent_hugepage

- name: Include DNS configuration tasks
  ansible.builtin.include_tasks: dns.yml

- name: Include package installation tasks
  ansible.builtin.include_tasks: packages.yml

- name: Include ufw.yml
  ansible.builtin.include_tasks: ufw.yml

- name: Include tsshd tasks
  ansible.builtin.include_tasks: tsshd.yml

- name: Include vps provider consoles enable services
  ansible.builtin.import_tasks: serial.yml

- name: Include maintenance tasks
  ansible.builtin.include_tasks: maintenance.yml

- name: Include MOTD tasks
  ansible.builtin.include_tasks:
    file: motd.yml
    apply:
      tags: motd
  tags:
    - motd

- name: Include dumbfile tasks
  ansible.builtin.include_tasks:
    file: dumbfile.yml
    apply:
      tags: dumbfile
  tags:
    - dumbfile

- name: Include reboot tasks
  ansible.builtin.include_tasks: reboot.yml
