---
- name: Find unmanaged sysctl.d configs
  ansible.builtin.find:
    paths: /etc/sysctl.d
    patterns: "*.conf"
    file_type: any
  register: sysctl_d_configs

- name: Remove unmanaged sysctl.d configs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ sysctl_d_configs.files }}"
  when: item.path != "/etc/sysctl.d/99-ansible-general.conf"
  register: sysctl_d_removed_configs

- name: Clear legacy sysctl.conf
  ansible.builtin.copy:
    dest: /etc/sysctl.conf
    mode: "0644"
    content: ""
  register: sysctl_conf_values

- name: Configure custom sysctl values
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-ansible-general.conf
    mode: "0644"
    content: |
      {% for item in sysctl_values %}
      {{ item.key }} = {{ item.value }}
      {% endfor %}
  register: sysctl_custom_values

- name: Apply sysctl values
  ansible.builtin.command:
    argv:
      - sysctl
      - --system
  changed_when: true
  when: >-
    sysctl_d_removed_configs.changed or
    sysctl_conf_values.changed or
    sysctl_custom_values.changed
