---
- name: Whattocommit Docker Container
  community.docker.docker_container:
    name: whattocommit
    image: mayurifag/whattocommit:main
    pull: true
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ whattocommit_available_externally }}"
      traefik.http.routers.whattocommit.rule: "Host(`{{ whattocommit_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.whattocommit.loadbalancer.server.port: "8080"
      traefik.http.routers.whattocommit.middlewares: "my-headers@file"
