---
- name: Delete Filerun directories
  file:
    path: "{{ filerun_data_directory }}"
    state: absent

- name: Create Filerun db directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ filerun_data_directory }}/"
    - "{{ filerun_data_directory }}/db"
    - "{{ filerun_data_directory }}/html"
    - "{{ filerun_data_directory }}/html/customizables"
    - "{{ filerun_data_directory }}/files"

- name: Filerun MariaDB Docker Container
  docker_container:
    name: filerun-mariadb
    image: mariadb:10.1
    pull: true
    recreate: yes
    volumes:
      - "{{ filerun_data_directory }}/db:/var/lib/mysql"
    env:
      MYSQL_DATABASE: filerundb
      MYSQL_USER: "{{ filerun_sql_user }}"
      MYSQL_PASSWORD: "{{ filerun_sql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ admin_userpassword }}"
      TZ: "{{ server_timezone }}"
    restart_policy: unless-stopped

- name: Template Filerun config.php
  template:
    src: config.php.j2
    dest: "{{ filerun_data_directory }}/html/customizables/config.php"

- name: Filerun Docker Container
  docker_container:
    name: filerun
    image: filerun/filerun
    pull: true
    recreate: yes
    volumes:
      - "{{ filerun_data_directory }}/html:/var/www/html"
      - "{{ filerun_data_directory }}/files:/user-files"
    links:
      - filerun-mariadb:filerun-mariadb
    env:
      TZ: "{{ server_timezone }}"
      FR_DB_HOST: filerun-mariadb
      FR_DB_PORT: "3306"
      FR_DB_NAME: filerundb
      FR_DB_USER: "{{ filerun_sql_user }}"
      FR_DB_PASS: "{{ filerun_sql_password }}"
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_USER_ID: '33'
      APACHE_RUN_GROUP_ID: '33'
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ filerun_available_externally }}"
      traefik.backend: "filerun"
      traefik.http.routers.filerun.rule: "Host(`{{ filerun_subdomain }}.{{ server_hostname }}`)"
      traefik.frontend.rule: "Host:{{ filerun_subdomain }}.{{ server_hostname }}"
      traefik.http.services.filerun.loadbalancer.server.port: "80"
      traefik.http.routers.filerun.middlewares: "my-headers@file,frameOptionsSameOrigin"
      traefik.http.middlewares.frameOptionsSameOrigin.headers.customFrameOptionsValue: "sameorigin"
