---
- name: "Set hostname to {{ server_hostname }}"
  hostname:
    name: "{{ server_hostname }}"

- name: "Set timezone to {{ server_timezone }}"
  timezone:
    name: "{{ server_timezone }}"

# - name: Ensure the locale en_US.UTF-8 exists
#   locale_gen:
#     name: en_US.UTF-8
#     state: present

# - name: Set en_US.UTF-8 as default locale
#   command: localectl set-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: Apply custom sysctl values
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    ignoreerrors: yes
    sysctl_set: yes
    reload: yes
    state: present
  with_items: "{{ sysctl_values }}"

# https://unix.stackexchange.com/a/368309
- name: clean sshd config out of legacy settings and warnings
  shell: |
    sed -i '/KeyRegenerationInterval/d' /etc/ssh/sshd_config
    sed -i '/ServerKeyBits/d' /etc/ssh/sshd_config
    sed -i '/RSAAuthentication/d' /etc/ssh/sshd_config
    sed -i '/RhostsRSAAuthentication/d' /etc/ssh/sshd_config
    sed -i '/UsePrivilegeSeparation/d' /etc/ssh/sshd_config

- name: restart sshd after changing configuration
  systemd:
    name: sshd
    state: restarted
