---
# Update all apt packages when playbook is run
keep_packages_updated: false

# Extra packages to install
mayurifag_general_extra_packages:
  - apt-transport-https
  - aptitude
  - curl
  - htop
  - unzip
  - wget
  - whois
  - linux-headers-{{ ansible_kernel }}
