---
- name: Delete OCIS directory
  ansible.builtin.file:
    path: "{{ ocis_data_directory }}"
    state: absent

- name: Create OCIS directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_uid }}"
    group: "{{ admin_gid }}"
  with_items:
    - "{{ ocis_data_directory }}/userfiles"
    - "{{ ocis_data_directory }}/config"

- name: OCIS Docker Container
  community.docker.docker_container:
    name: ocis
    image: "{{ ocis_container }}:{{ ocis_version }}"
    pull: true
    recreate: yes
    volumes:
      - "{{ ocis_data_directory }}/config:/etc/ocis"
      - "{{ ocis_data_directory }}/userfiles:/var/lib/ocis"
    entrypoint:
      - /bin/sh
    command: ["-c", "ocis init || true; ocis server"]
    env:
      TZ: "{{ server_timezone }}"
      OCIS_URL: "https://{{ ocis_subdomain }}.{{ server_hostname }}"
      OCIS_LOG_LEVEL: "info"
      OCIS_LOG_COLOR: "false"
      PROXY_TLS: "false"
      OCIS_INSECURE: "false"
      PROXY_ENABLE_BASIC_AUTH: "false"
      IDM_ADMIN_PASSWORD: "{{ admin_userpassword }}"
      IDM_CREATE_DEMO_USERS: "false"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ ocis_available_externally }}"
      traefik.http.routers.ocis.rule: "Host(`{{ ocis_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.ocis.loadbalancer.server.port: "9200"
      traefik.http.routers.ocis.middlewares: "my-headers@file"
