---
mise_tools:
  - name: opencode
    version: latest
  - name: lazydocker
    version: latest
mise_opencode_users:
  - name: root
    home: /root
    group: root
  - name: "{{ admin_username }}"
    home: "/home/{{ admin_username }}"
    group: "{{ admin_username }}"
mise_opencode_config:
  $schema: https://opencode.ai/config.json
  model: openai/gpt-5.5
  small_model: openai/gpt-5.3-codex-spark
  default_agent: build
  enabled_providers:
    - openai
  agent:
    build:
      mode: primary
      model: openai/gpt-5.5
      description: Build (GPT 5.5 Medium)
    fast:
      mode: primary
      model: openai/gpt-5.3-codex-spark
      description: Fast (GPT 5.3 Codex Spark)
    title:
      model: openai/gpt-5.3-codex-spark
      options:
        reasoningEffort: low
    plan:
      disable: true
  mcp:
    context7:
      type: remote
      url: https://mcp.context7.com/mcp
      enabled: true
  permission: allow
