---
- name: Create Organizr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ organizr_data_directory }}"

- name: Create Organizr container
  docker_container:
    name: organizr
    image: organizr/organizr:latest
    pull: true
    volumes:
      - "{{ organizr_data_directory }}:/config:rw"
    env:
      PUID: "{{ organizr_user_id }}"
      PGID: "{{ organizr_group_id }}"
      TZ: "{{ server_timezone }}"
    ports:
      - "{{ organizr_port_http }}:80"
      - "{{ organizr_port_https }}:443"
    restart_policy: unless-stopped
    memory: "{{ organizr_memory }}"
    labels:
      traefik.enable: "{{ organizr_available_externally }}"
      traefik.http.routers.organizr.rule: "Host(`{{ organizr_hostname }}.{{ server_hostname }}`)"
      # traefik.http.routers.organizr.tls.certresolver: "letsencrypt"
      # traefik.http.routers.organizr.tls.domains[0].main: "{{ server_hostname }}"
      # traefik.http.routers.organizr.tls.domains[0].sans: "*.{{ server_hostname }}"
      traefik.http.services.organizr.loadbalancer.server.port: "80"
