---
wireguard_enabled: true
wireguard_available_externally: "true"

wireguard_docker_image: weejewel/wg-easy:latest
wireguard_data_directory: "{{ docker_home }}/wireguard"
wireguard_subdomain: "wg"

wireguard_memory: 1g

# https://www.reddit.com/r/WireGuard/comments/1290vyt/wgeasy_and_android/
