---
- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Add admin user with wheel group
  ansible.builtin.user:
    name: "{{ admin_username }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash

- name: Set admin user password
  ansible.builtin.command: 'echo "{{ admin_username }}:{{ admin_userpassword }}" | chpasswd'

- name: Set root password
  ansible.builtin.command: 'echo "root:{{ root_userpassword }}" | chpasswd'

- name: Create user .ssh directory
  ansible.builtin.file:
    path: "~{{ admin_username }}/.ssh"
    mode: "0700"
    state: directory
    owner: "{{ admin_username }}"

- name: Create user authorized_keys
  ansible.builtin.template:
    src: "templates/authorized_keys.j2"
    dest: "~{{ admin_username }}/.ssh/authorized_keys"
    owner: "{{ admin_username }}"
    mode: "0400"

- name: Apply bash settings for admin user
  ansible.builtin.template:
    src: "templates/.bashrc"
    dest: "/home/{{ admin_username }}/.bashrc"
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: "0644"

- name: Apply bash settings for root user
  ansible.builtin.template:
    src: "templates/.bashrc"
    dest: "/root/.bashrc"
    owner: root
    group: root
    mode: "0644"

- name: Configure SSH daemon
  ansible.builtin.template:
    src: "templates/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart sshd
