---
- name: Create Homer Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homer_data_directory }}/assets"

- name: Template Homer config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ homer_data_directory }}/assets/config.yml"

- name: Create Homer container
  community.docker.docker_container:
    name: homer
    image: "{{ homer_docker_image }}"
    pull: true
    volumes:
      - "{{ homer_data_directory }}/assets:/www/assets:rw"
    restart_policy: unless-stopped
    memory: "{{ homer_memory }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homer.rule: "Host(`{{ homer_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.homer.loadbalancer.server.port: "8080"
      traefik.http.routers.homer.middlewares: "auth@file,my-headers@file"
