- name: Add official nginx apt key.
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
- name: Add official nginx repo.
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/debian/ {{ ansible_distribution_release }} nginx"
    state: present
- name: Install nginx
  apt:
    pkg: nginx
    update_cache: true
  notify: start nginx
# - name: '/etc/nginx/sites-enabled/default: remove'
#   file: path=/etc/nginx/sites-enabled/default state=absent
# - name: '/etc/nginx/sites-available/default: remove'
#   file: path=/etc/nginx/sites-available/default state=absent
- name: 'Remove default nginx config'
  file: path=/etc/nginx/conf.d/default.conf state=absent
- name: 'Initialize main configuration'
  template: src=roles/nginx/templates/main.j2 dest=/etc/nginx/conf.d/main.conf
# TODO: gzip params maybe!
- name: '/etc/nginx/nginx.conf remove all ssl_ params'
  lineinfile: dest=/etc/nginx/nginx.conf regexp="^[\s#]*ssl_" state=absent
- name: '/etc/nginx/extra'
  shell: mkdir -p /etc/nginx/extra
- name: '/etc/nginx/extra/security'
  template: src=roles/nginx/templates/security.j2 dest=/etc/nginx/extra/security
- name: '/etc/nginx/extra/ssl.conf'
  template: src=roles/nginx/templates/ssl.j2 dest=/etc/nginx/extra/ssl
- name: '/etc/nginx/extra/global_auth'
  template: src=roles/nginx/templates/global_auth.j2 dest=/etc/nginx/extra/global_auth
- name: '/etc/nginx/extra/redirect_to_https'
  template: src=roles/nginx/templates/redirect_to_https.j2 dest=/etc/nginx/extra/redirect_to_https
# - name: 'enable HPKP'
#   shell: echo "add_header Public-Key-Pins 'pin-sha256=\"$(openssl x509 -in /etc/ssl/ansible/mayurifag.ru.pem -pubkey -noout | openssl rsa -pubin -outform der | openssl dgst -sha256 -binary | base64)\"; pin-sha256=\"false\"; max-age=2592000';" >> /etc/nginx/extra/security
#   when: nginx.hpkp_sha256
- name: 'blacklist.conf'
  template: src=roles/nginx/templates/blacklist.conf.j2 dest=/tmp/blacklist.conf
- name: 'blockips.conf'
  template: src=roles/nginx/templates/blockips.conf.j2 dest=/tmp/blockips.conf
- name: 'blacklist.conf install'
  shell: 'curl -f -o /etc/nginx/conf.d/blacklist.conf https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blacklist.conf || cp /tmp/blacklist.conf /etc/nginx/conf.d/blacklist.conf'
- name: 'blockips.conf install'
  shell: 'curl -f -o /etc/nginx/conf.d/blockips.conf https://raw.githubusercontent.com/mariusv/nginx-badbot-blocker/master/blockips.conf || cp /tmp/blockips.conf /etc/nginx/conf.d/blockips.conf'
  notify: restart nginx
- name: Create global htpasswd file
  htpasswd:
    path: /etc/nginx/global_htpasswd
    name: "{{ nginx_global_auth_username }}"
    password: "{{ nginx_global_auth_password }}"

# TODO: http v2 everywhere
# TODO: stub maybe
