---
glance_enabled: true
glance_subdomain: "rss"
glance_image: "glanceapp/glance:latest"
glance_memory: "256m"
glance_data_directory: "{{ docker_home }}/glance"

# Get a GitHub token at https://github.com/settings/tokens (no scopes needed for public repos)
glance_github_token: "change_this_github_token"

# Get a GitHub token with notifications scope for github-notifications widget
glance_github_notifications_token: "change_this_github_notifications_token"

# Get a WAQI token at https://aqicn.org/data-platform/token/
glance_waqi_token: "change_this_waqi_token"
