---
- name: Disable SWAP
  ansible.builtin.shell: |
    swapoff -a

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
