---
lldap_enabled: true

lldap_subdomain: "ldap"
lldap_data_directory: "{{ docker_home }}/lldap"
lldap_port: 17170

lldap_image: lldap/lldap:latest
lldap_memory: 512m
lldap_reset_data: false

lldap_ignored_user_attributes:
  - gidnumber
  - openclouduserenabled
  - opencloudusertype
  - text
  - uidnumber
  - uniquemember
lldap_ignored_group_attributes:
  - openclouduuid
