---
wallabag_enabled: true
wallabag_available_externally: "true"

wallabag_data_directory: "{{ docker_home }}/wallabag"
wallabag_port: "7780"
wallabag_hostname: "wallabag"

# specs
wallabag_memory: 1g
