---
- name: Shadowsocks + xray-plugin Docker Container
  docker_container:
    name: ss-xray
    image: mazy/ss-xray:v1.13.1-v1.5.3-0
    pull: true
    env:
      HOST: "{{ shadowsocks_subdomain }}.{{ server_hostname }}"
      SERVER_ADDR: "{{ shadowsocks_address }}"
      PASSWORD: "{{ shadowsocks_password }}"
      PLUGIN: "{{ shadowsocks_plugin }}"
      PLUGIN_OPTS: "{{ shadowsocks_plugin_opts }}"
      METHOD: "{{ shadowsocks_encrypt_method }}"
    restart_policy: unless-stopped
    memory: "{{ shadowsocks_memory }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.ss-xray.rule: "Host(`{{ shadowsocks_subdomain }}.{{ server_hostname }}`)"
      traefik.http.routers.ss-xray.tls.certresolver: "letsencrypt"
      traefik.http.services.ss-xray.loadbalancer.server.port: "1080"
