- name: Update distro
  apt: update_cache=yes upgrade=yes

- name: Disable recommended packages
  shell: echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/00norecommends

- name: Install libc-bin
  apt: pkg=libc-bin state=latest
- name: Install curl
  apt: pkg=curl state=latest
- name: Install ntp
  apt: pkg=ntp state=latest
- name: Install whois
  apt: pkg=whois state=latest
- name: Install MySQL
  apt: pkg=mysql-server state=latest
- name: Install python-mysqldb
  apt: pkg=python-mysqldb state=latest
- name: Enable english locales
  lineinfile: dest=/etc/locale.gen regexp="^#?\s*en_US.UTF-8\s*UTF-8" line="en_US.UTF-8 UTF-8"
- name: Regenerate locales
  shell: locale-gen
