- name: Update distro
  apt: update_cache=yes upgrade=yes

- name: Disable recommended packages
  shell: echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/00norecommends

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: ["unzip", "apt-transport-https", "libc-bin", "curl", "ntp", "whois", "ca-certificates", "acl", "sudo", "libuv1-dev", "linux-headers-{{ ansible_kernel }}"]

# maybe add russian locale
- name: Enable english locales
  lineinfile: dest=/etc/locale.gen regexp="^#?\s*en_US.UTF-8\s*UTF-8" line="en_US.UTF-8 UTF-8"
- name: Regenerate locales
  shell: locale-gen

- name: Set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow
