- name: Update distro
  apt: update_cache=yes upgrade=yes

- name: Disable recommended packages
  shell: echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/00norecommends

- name: Install libc-bin
  apt: pkg=libc-bin state=latest
- name: Install curl
  apt: pkg=curl state=latest
- name: Install ntp
  apt: pkg=ntp state=latest
- name: Install whois
  apt: pkg=whois state=latest
