---
- name: Mini-QR Docker Container
  community.docker.docker_container:
    name: mini-qr
    image: "{{ qr_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    memory: "{{ qr_memory }}"
    networks:
      - name: "web"
    env:
      VITE_HIDE_CREDITS: "true"
      VITE_DEFAULT_PRESET: "lyqht"
    labels:
      traefik.enable: "true"
      traefik.http.routers.mini-qr.rule: "Host(`{{ qr_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.mini-qr.loadbalancer.server.port: "8080"
      traefik.http.routers.mini-qr.middlewares: "tinyauth@docker"
      com.centurylinklabs.watchtower.enable: "true"
