---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - security
    # - postfix
    # - dovecot
    # - opendkim
    # - dspam
    # - zpush
    # - roundcube
    # - ddclient
    # - duplicity
    # - owncloud
