---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - robertdebock.bootstrap

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - base
    - sysctl-tweaks
    - maildb
    - security
    - letsencrypt
    - dante
    - postfix
    - dovecot
    - opendkim
    - nginx
    - jffz.netdata
    - netdata
    - shadowsocks
    - php
    - redis
    - nextcloud
    - rspamd
    - rainloop
    - wireguard

    # TODO:
    # - jitsi # idk something for video calling
    # - git # idk gitlab gitea
    # - wallabag

    # Ideas:
    # - bitwarden
    # - web analytics # matomo or something else
    # - rocket.chat
    # - torrents-api # Jackett
    # - finances # https://github.com/firefly-iii/firefly-iii
    # - audioplayer # ampache
  vars_files:
    - sensitive_variables.yaml
