---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
  - name: 'Install python to make ansible working on clean system'
    raw: 'DEBIAN_FRONTEND=noninteractive apt-get install -y python python-apt'

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - base
    - sysctl-tweaks
    - security
    - dante
    - maildb
    - letsencrypt
    - postfix
    - dovecot
    - opendkim
    - nginx
    - jffz.netdata
    - netdata
    - shadowsocks
    - php
    - redis
    - nextcloud
    - rspamd # beware install after redis
    - rainloop
    - wireguard
