---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - base
    - sysctl-tweaks
    - security
    - dante
    - maildb
    - letsencrypt
    - postfix
    - dovecot
    - opendkim
    - nginx
    - netdata
    - jffz.netdata
    - shadowsocks
    - php
    - redis
    - nextcloud
    - rspamd # beware install after redis
    - rainloop
    - wireguard
