---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
  - name: 'Install python to make ansible working on clean system'
    raw: 'DEBIAN_FRONTEND=noninteractive apt-get install -y python python-apt'

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - base
    - sysctl-tweaks
    - maildb
    - security
    - letsencrypt
    - dante
    - postfix
    - dovecot
    - opendkim
    - nginx
    - jffz.netdata
    - netdata
    - shadowsocks
    - php
    - redis
    - nextcloud
    - rspamd
    - rainloop
    - wireguard

    # TODO:
    # - jitsi # idk something for video calling
    # - rocket.chat
    # - git # idk gitlab gitea
  vars_files:
    - sensitive_variables.yaml
