---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - base
    - sysctl-tweaks
    - security
    - letsencrypt
    - dante
    - maildb
    - postfix
    - dovecot
    - opendkim
    - nginx


    # - rspamd
    # - zpush
    # - roundcube
    # - ddclient
    # - duplicity
    # - owncloud
