---
- name: Cloudflare DNS + Email Routing
  ansible.builtin.import_tasks: dns.yml
  tags: dns

- name: Traefik prerequisites
  ansible.builtin.import_tasks: traefik_prepare.yml

- name: Sablier
  ansible.builtin.import_tasks: sablier.yml

- name: CrowdSec
  ansible.builtin.import_tasks: crowdsec.yml

- name: Traefik
  ansible.builtin.import_tasks: traefik_task.yml
