---
# - name: Stop traefik container if it exists
#   community.docker.docker_container:
#     name: traefik
#     state: stopped

- name: Traefik Docker Container
  community.docker.docker_container:
    name: traefik
    image: "{{ traefik_docker_image }}"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "{{ traefik_dynamic_configs_directory }}:/etc/traefik/dynamic_configs:ro"
      - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
      - "{{ traefik_logs_directory }}:/var/log/traefik:rw"
      - "{{ traefik_plugins_storage_directory }}:/plugins-storage:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env: "{{ traefik_environment_variables }}"
    command:
      - sh
      - -c
      - >-
        i=0; until nc -z crowdsec 8080 && nc -z crowdsec 7422 ||
        [ "$i" -ge {{ traefik_crowdsec_startup_wait_seconds }} ]; do
        i=$((i + 1)); sleep 1; done;
        exec traefik
    restart_policy: always
    networks:
      - name: "web"
    memory: "{{ traefik_memory }}"
    recreate: "{{ template_config.changed | default(false) }}"
    stop_timeout: 30
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "tinyauth@docker"

- name: Ensure logrotate is installed
  ansible.builtin.apt:
    name: logrotate
    state: present

- name: Configure Traefik log rotation
  ansible.builtin.copy:
    dest: /etc/logrotate.d/traefik
    content: |
      {{ traefik_logs_directory }}/*.log
      {
        daily
        rotate 7
        missingok
        notifempty
        compress
        delaycompress
        postrotate
          docker kill --signal="USR1" traefik
        endscript
      }
    mode: "0644"
