---
# - name: Stop traefik container if it exists
#   community.docker.docker_container:
#     name: traefik
#     state: stopped

- name: Remove Traefik logs
  ansible.builtin.file:
    path: "{{ traefik_logs_directory }}"
    state: absent
  register: traefik_logs_cleanup

- name: Create Traefik Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_dynamic_configs_directory }}"
    - "{{ traefik_data_directory }}/letsencrypt"
    - "{{ traefik_logs_directory }}"

- name: Ensure Traefik access log exists
  ansible.builtin.copy:
    dest: "{{ traefik_logs_directory }}/access.log"
    content: ""
    force: no
    mode: "0644"

- name: Create Traefik config.toml from template
  ansible.builtin.template:
    src: traefik.toml.j2
    dest: "{{ traefik_data_directory }}/traefik.toml"
  register: template_config

- name: Create Traefik dynamic configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ traefik_dynamic_configs_directory }}/{{ item.path |
      regex_replace('\\.j2$', '') }}"
    force: yes
  loop: "{{ query('filetree', '../templates/dynamic_configs') }}"
  when: item.state == 'file'

- name: Create web network
  community.docker.docker_network:
    name: web
    state: present

- name: Traefik Docker Container
  community.docker.docker_container:
    name: traefik
    image: "{{ traefik_docker_image }}"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "{{ traefik_dynamic_configs_directory }}:/etc/traefik/dynamic_configs:ro"
      - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
      - "{{ traefik_logs_directory }}:/var/log/traefik:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env: "{{ traefik_environment_variables }}"
    restart_policy: always
    networks:
      - name: "web"
    memory: "{{ traefik_memory }}"
    recreate: "{{ template_config.changed or (traefik_logs_cleanup.changed | default(false)) }}"
    stop_timeout: 30
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`{{ traefik_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: "tinyauth@docker"

- name: Ensure logrotate is installed
  ansible.builtin.apt:
    name: logrotate
    state: present

- name: Configure Traefik log rotation
  ansible.builtin.copy:
    dest: /etc/logrotate.d/traefik
    content: |
      {{ traefik_logs_directory }}/*.log
      {
        daily
        rotate 7
        missingok
        notifempty
        compress
        delaycompress
        postrotate
          docker kill --signal="USR1" traefik
        endscript
      }
    mode: "0644"
