---
- name: Create Traefik Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_dynamic_configs_directory }}"
    - "{{ traefik_data_directory }}/letsencrypt"
    - "{{ traefik_logs_directory }}"
    - "{{ traefik_plugins_storage_directory }}"

- name: Ensure Traefik access log exists
  ansible.builtin.copy:
    dest: "{{ traefik_logs_directory }}/access.log"
    content: ""
    force: no
    mode: "0644"

- name: Create Traefik config.toml from template
  ansible.builtin.template:
    src: traefik.toml.j2
    dest: "{{ traefik_data_directory }}/traefik.toml"
  register: template_config

- name: Create Traefik dynamic configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ traefik_dynamic_configs_directory }}/{{ item.path |
      regex_replace('\\.j2$', '') }}"
    force: yes
  loop: "{{ query('filetree', '../templates/dynamic_configs') }}"
  when: item.state == 'file'

- name: Remove stale encoded characters config
  ansible.builtin.file:
    path: "{{ traefik_dynamic_configs_directory }}/encoded-characters.toml"
    state: absent

- name: Create web network
  community.docker.docker_network:
    name: web
    state: present
