---
tinyauth_enabled: true

tinyauth_data_directory: "{{ docker_home }}/tinyauth"
tinyauth_docker_image: ghcr.io/tinyauthapp/tinyauth:v5.2.0
tinyauth_subdomain: "auth"

tinyauth_memory: 512m

tinyauth_google_enabled: false
