- name: Add gpg key
  apt_key:
    url: https://rspamd.com/apt-stable/gpg.key
    state: present

- name: Add repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: rspamd
  with_items:
    - deb     http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main
    - deb-src http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main

- name: "/etc/postfix/main.cf: smtpd_milters"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_milters\s=" line="smtpd_milters = inet:localhost:11332"
- name: Add milter protocol = 6 to main.cf (rspamd protocol)
  lineinfile:
    state: present
    dest: /etc/postfix/main.cf
    regexp: '^milter_protocol'
    line: 'milter_protocol = 6'

- name: Add non_smtpd_milters = $smtpd_milters
  lineinfile:
    state: present
    dest: /etc/postfix/main.cf
    regexp: '^non_smtpd_milters'
    line: 'non_smtpd_milters = $smtpd_milters'

- name: Add milter_default_action
  lineinfile:
    state: present
    dest: /etc/postfix/main.cf
    regexp: '^milter_default_action'
    line: 'milter_default_action = accept'

- name: Add milter_mail_macros
  lineinfile:
    state: present
    dest: /etc/postfix/main.cf
    regexp: '^milter_mail_macros'
    line: 'milter_mail_macros =  i {mail_addr} {client_addr} {client_name} {auth_authen}'

- name: Install package
  apt:
    name: rspamd
    state: present
    install_recommends: false
    update_cache: true

- name: Clean dkim directory if exists
  file: path=/var/lib/rspamd/dkim/ state=absent

- name: Create directory for dkim files
  file: path=/var/lib/rspamd/dkim/ state=directory

- name: Generate DKIM keys
  shell: 'rspamadm dkim_keygen -b 2048 -s mail -k /var/lib/rspamd/dkim/mail.key | sudo tee -a  /var/lib/rspamd/dkim/mail.pub'

# TODO: make idempotent/not shell
- name: Chown dkim folder
  shell: 'chown -R _rspamd: /var/lib/rspamd/dkim'

- name: Make dkim files readonly
  shell: 'chmod 440 /var/lib/rspamd/dkim/*'

- name: copy rspamd config
  copy:
    src: rspamd/local.d/
    dest: /etc/rspamd/local.d/

- name: "Generate proxy configuration for rspamd"
  template:
    dest: /etc/rspamd/local.d/worker-controller.inc
    src: "templates/worker-controller.inc.j2"

- name: "[NGINX] -  generate rspamd configuration for nginx"
  template:
    dest: /etc/nginx/conf.d/rspamd.conf
    src: "templates/rspamd.conf.j2"
  notify: reload nginx

# verify everything is running
- name: verify services are running in dependency order
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  loop:
    - redis
    - rspamd
    - nginx


# Test everything is working [https://workaround.org/ispmail/stretch/filtering-out-spam-with-rspamd]
# wget http://spamassassin.apache.org/gtube/gtube.txt
# sendmail me@mayuirfag.ru < gtube.txt
