---
php_ver: 7.3
php_dir: "/etc/php/7.3"
php_bin: "php-fpm7.3"
php_pkg_apcu: "php-apcu"
php_pkg_spe:
  - "php-imap"
  - "php-imagick"
  - "php-redis"
  - "php7.3-xml"
  - "php7.3-zip"
  - "php7.3-mbstring"
php_socket: "/run/php/php7.3-fpm.sock"
