---
- name: Get admin user info
  ansible.builtin.getent:
    database: passwd
    key: "{{ admin_username }}"

- name: Create SnapOtter Directory
  ansible.builtin.file:
    path: "{{ snapotter_data_directory }}"
    state: directory
    owner: "{{ ansible_facts.getent_passwd[admin_username][1] }}"
    group: "{{ ansible_facts.getent_passwd[admin_username][2] }}"
    mode: "0755"

- name: SnapOtter Docker Container
  community.docker.docker_container:
    name: snapotter
    image: "{{ snapotter_image }}"
    state: started
    pull: true
    recreate: true
    restart_policy: unless-stopped
    memory: "{{ snapotter_memory }}"
    volumes:
      - "{{ snapotter_data_directory }}:/data"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -sf --max-time 5 http://localhost:1349/api/v1/health || exit 1
      interval: 5m
      timeout: 5s
      retries: 180
      start_period: 30s
      start_interval: 2s
    networks:
      - name: "web"
    env:
      AUTH_ENABLED: "false"
      TRUST_PROXY: "true"
      APP_NAME: "{{ snapotter_app_name }}"
      DEFAULT_THEME: "{{ snapotter_default_theme }}"
    labels:
      sablier.enable: "true"
      sablier.group: snapotter
      traefik.enable: "true"
      traefik.docker.allownonrunning: "true"
      traefik.http.middlewares.snapotter-sablier.plugin.sablier.group: "snapotter"
      traefik.http.middlewares.snapotter-sablier.plugin.sablier.sablierUrl: "http://sablier:10000"
      traefik.http.middlewares.snapotter-sablier.plugin.sablier.sessionDuration: "1h"
      traefik.http.middlewares.snapotter-sablier.plugin.sablier.dynamic.displayName: "images"
      traefik.http.middlewares.snapotter-sablier.plugin.sablier.dynamic.refreshFrequency: "2s"
      traefik.http.routers.snapotter.rule: "Host(`{{ snapotter_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.snapotter.loadbalancer.server.port: "1349"
      traefik.http.routers.snapotter.middlewares: "tinyauth@docker,snapotter-sablier@docker"
      com.centurylinklabs.watchtower.enable: "true"

- name: Stop SnapOtter Docker Container
  ansible.builtin.command: docker stop snapotter
  changed_when: true
