---
opencloud_enabled: true

opencloud_subdomain: "cloud"

opencloud_image: "opencloudeu/opencloud-rolling:6"

opencloud_data_directory: "{{ docker_home }}/opencloud"
opencloud_files_directory: "{{ files_home }}/"

opencloud_log_level: "warn"
opencloud_disable_versioning: "true"
opencloud_posix_propagator: "async"
opencloud_posix_scan_debounce_delay: "10s"
opencloud_posix_inotify_stats_frequency: "15m"

opencloud_nats_image: "nats:2-alpine"
opencloud_nats_box_image: "natsio/nats-box:latest"
opencloud_nats_container_name: "opencloud-nats"
opencloud_nats_data_directory: "{{ opencloud_data_directory }}/nats"
opencloud_nats_store_max_file: "1G"
opencloud_nats_store_max_mem: "256M"
