---
opencloud_enabled: true

opencloud_subdomain: "cloud"

opencloud_image: "opencloudeu/opencloud-rolling:6"

opencloud_data_directory: "{{ docker_home }}/opencloud"
opencloud_files_directory: "{{ files_home }}/"

opencloud_log_level: "warn"
