---
- name: Create Wallabag Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ wallabag_data_directory }}/data"
    - "{{ wallabag_data_directory }}/images"

- name: Wallabag Docker Container
  docker_container:
    name: wallabag
    image: wallabag/wallabag:latest
    pull: true
    volumes:
      - "{{ wallabag_data_directory }}/data:/var/www/wallabag/data:rw"
      - "{{ wallabag_data_directory }}/images:/var/www/wallabag/web/assets/images:rw"
    env:
      SYMFONY__ENV__DOMAIN_NAME: "https://{{ wallabag_subdomain }}.{{ server_hostname }}"
    restart_policy: unless-stopped
    memory: "{{ wallabag_memory }}"
    labels:
      traefik.enable: "{{ wallabag_available_externally }}"
      traefik.http.routers.wallabag.rule: "Host(`{{ wallabag_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.wallabag.loadbalancer.server.port: "80"
      traefik.http.routers.wallabag.middlewares: "my-headers@file"
