---
- fail:
    msg: "Only Debian supported for now"
  when: ansible_distribution != 'Debian'

- include_tasks:
  file: wireguard-install.yml

- include_tasks:
  file: wireguard-setup.yml

- include_tasks:
  file: wireguard-fetch-profiles.yml
