---
- name: Delete wireguard directories
  ansible.builtin.file:
    path: "{{ wireguard_data_directory }}/"
    state: absent

- name: Create wireguard data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ wireguard_data_directory }}/"

- name: Wireguard-Easy Docker Container
  community.docker.docker_container:
    name: wg-easy
    image: "{{ wireguard_docker_image }}"
    pull: true
    recreate: true
    sysctls:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
    memory: "{{ wireguard_memory }}"
    env:
      "PASSWORD_HASH": "{{ wireguard_password_hash }}"
      "WG_HOST": "{{ wireguard_subdomain }}.{{ server_hostname }}"
      "WG_DEFAULT_DNS": "1.1.1.1, 8.8.8.8, 8.8.4.4"
      "LANG": "en"
      "PORT": "51821"
      "WG_PORT": "51820"
      "WG_PERSISTENT_KEEPALIVE": "60"
      "UI_TRAFFIC_STATS": "true"
      "UI_CHART_TYPE": "1"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - "{{ wireguard_data_directory }}/:/etc/wireguard"
    labels:
      traefik.enable: "{{ wireguard_available_externally }}"
      traefik.http.routers.wg-easy.rule: "Host(`{{ wireguard_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.wg-easy.loadbalancer.server.port: "51821"
      traefik.http.routers.wg-easy.middlewares: "secure-headers@file"
